# **Tugas - 3 Modelling (Logistic Regression) dan Testing**

In [ ]:
import sklearn
print(sklearn.__version__)

1.5.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pickle
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/My Drive/PPW-A/report/Tugas-PPW/hasil_preprocesing.csv")
df.head()

,judul,isi,tanggal,kategori,Hasil cleansing,Hasil case_folding,tokenize,Hasil stopword
0,18 Tim yang Lolos FFWS Global Finals 2024 di B...,Jakarta - Rangkaian pertandingan di FFWS SEA 2...,"Rabu, 16 Okt 2024 19:30 WIB",Games,Jakarta Rangkaian pertandingan di FFWS SEA F...,jakarta rangkaian pertandingan di ffws sea f...,"['jakarta', 'rangkaian', 'pertandingan', 'di',...",jakarta rangkaian pertandingan ffws sea fall s...
1,Ampun Bang Jago! Zuckerberg Klaim Pemain Handa...,"Jakarta - CEO Meta Mark Zuckerberg, cukup perc...","Rabu, 16 Okt 2024 17:50 WIB",Games,Jakarta CEO Meta Mark Zuckerberg cukup percay...,jakarta ceo meta mark zuckerberg cukup percay...,"['jakarta', 'ceo', 'meta', 'mark', 'zuckerberg...",jakarta ceo meta mark zuckerberg percaya kemam...
2,"20 Game Horor Terbaik Tahun 2000an, Udah Perna...",Jakarta - Game horor selalu punya daya tarikny...,"Rabu, 16 Okt 2024 14:20 WIB",Games,Jakarta Game horor selalu punya daya tariknya...,jakarta game horor selalu punya daya tariknya...,"['jakarta', 'game', 'horor', 'selalu', 'punya'...",jakarta game horor daya tariknya penikmatnya b...
3,"Begini Cara Dapat Skin Zhou Yu HOK Gratis, Gam...",Jakarta - Ternyata cara dapat skin Zhou Yu Hon...,"Rabu, 16 Okt 2024 12:15 WIB",Games,Jakarta Ternyata cara dapat skin Zhou Yu Hono...,jakarta ternyata cara dapat skin zhou yu hono...,"['jakarta', 'ternyata', 'cara', 'dapat', 'skin...",jakarta skin zhou yu honor of kings hok gratis...
4,"Gagal Juara FFWS SEA 2024 Fall, Wakil RI: Kita...","Jakarta - Tampil di depan ribuan pendukungnya,...","Selasa, 15 Okt 2024 17:36 WIB",Games,Jakarta Tampil di depan ribuan pendukungnya t...,jakarta tampil di depan ribuan pendukungnya t...,"['jakarta', 'tampil', 'di', 'depan', 'ribuan',...",jakarta tampil ribuan pendukungnya wakil indon...

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Transformasi data kategorik
label_encoder = LabelEncoder()
df.loc[:, 'kategori_encoded'] = label_encoder.fit_transform(df['kategori'])

# Menampilkan nilai sebelum dan sesudah konversi
print("\nNilai sebelum dan sesudah konversi:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nDataFrame setelah Label Encoding:")
df

Nilai sebelum dan sesudah konversi:
{'Games': 0, 'Sepak Bola': 1}

DataFrame setelah Label Encoding:

,judul,isi,tanggal,kategori,Hasil cleansing,Hasil case_folding,tokenize,Hasil stopword,kategori_encoded
0,18 Tim yang Lolos FFWS Global Finals 2024 di B...,Jakarta - Rangkaian pertandingan di FFWS SEA 2...,"Rabu, 16 Okt 2024 19:30 WIB",Games,Jakarta Rangkaian pertandingan di FFWS SEA F...,jakarta rangkaian pertandingan di ffws sea f...,"['jakarta', 'rangkaian', 'pertandingan', 'di',...",jakarta rangkaian pertandingan ffws sea fall s...,0
1,Ampun Bang Jago! Zuckerberg Klaim Pemain Handa...,"Jakarta - CEO Meta Mark Zuckerberg, cukup perc...","Rabu, 16 Okt 2024 17:50 WIB",Games,Jakarta CEO Meta Mark Zuckerberg cukup percay...,jakarta ceo meta mark zuckerberg cukup percay...,"['jakarta', 'ceo', 'meta', 'mark', 'zuckerberg...",jakarta ceo meta mark zuckerberg percaya kemam...,0
2,"20 Game Horor Terbaik Tahun 2000an, Udah Perna...",Jakarta - Game horor selalu punya daya tarikny...,"Rabu, 16 Okt 2024 14:20 WIB",Games,Jakarta Game horor selalu punya daya tariknya...,jakarta game horor selalu punya daya tariknya...,"['jakarta', 'game', 'horor', 'selalu', 'punya'...",jakarta game horor daya tariknya penikmatnya b...,0
3,"Begini Cara Dapat Skin Zhou Yu HOK Gratis, Gam...",Jakarta - Ternyata cara dapat skin Zhou Yu Hon...,"Rabu, 16 Okt 2024 12:15 WIB",Games,Jakarta Ternyata cara dapat skin Zhou Yu Hono...,jakarta ternyata cara dapat skin zhou yu hono...,"['jakarta', 'ternyata', 'cara', 'dapat', 'skin...",jakarta skin zhou yu honor of kings hok gratis...,0
4,"Gagal Juara FFWS SEA 2024 Fall, Wakil RI: Kita...","Jakarta - Tampil di depan ribuan pendukungnya,...","Selasa, 15 Okt 2024 17:36 WIB",Games,Jakarta Tampil di depan ribuan pendukungnya t...,jakarta tampil di depan ribuan pendukungnya t...,"['jakarta', 'tampil', 'di', 'depan', 'ribuan',...",jakarta tampil ribuan pendukungnya wakil indon...,0
...,...,...,...,...,...,...,...,...,...
95,Rating Pemain China Vs Indonesia: Thom Haye Te...,Jakarta - China vs Indonesia tuntas 2-1 di lan...,"Rabu, 16 Okt 2024 12:00 WIB",Sepak Bola,Jakarta China vs Indonesia tuntas di lanjuta...,jakarta china vs indonesia tuntas di lanjuta...,"['jakarta', 'china', 'vs', 'indonesia', 'tunta...",jakarta china vs indonesia tuntas lanjutan kua...,1
96,China Vs Indonesia: Coret Eliano Reijnders Blu...,Qingdao - Keputusan mencoret Eliano Reijnders ...,"Rabu, 16 Okt 2024 11:40 WIB",Sepak Bola,Qingdao Keputusan mencoret Eliano Reijnders s...,qingdao keputusan mencoret eliano reijnders s...,"['qingdao', 'keputusan', 'mencoret', 'eliano',...",qingdao keputusan mencoret eliano reijnders me...,1
97,Dumfries Akui Performanya Lebih Baik di Timnas...,"Jakarta - Denzel Dumfries mengakui, performany...","Rabu, 16 Okt 2024 11:20 WIB",Sepak Bola,Jakarta Denzel Dumfries mengakui performanya ...,jakarta denzel dumfries mengakui performanya ...,"['jakarta', 'denzel', 'dumfries', 'mengakui', ...",jakarta denzel dumfries mengakui performanya t...,1
98,Hasil Lengkap-Klasemen Kualifikasi Piala Dunia...,Jakarta - Matchday 4 di babak ketiga kualifika...,"Rabu, 16 Okt 2024 11:00 WIB",Sepak Bola,Jakarta Matchday di babak ketiga kualifikasi...,jakarta matchday di babak ketiga kualifikasi...,"['jakarta', 'matchday', 'di', 'babak', 'ketiga...",jakarta matchday babak ketiga kualifikasi pial...,1
99,Spanyol Vs Serbia: De la Fuente Turunkan Start...,Jakarta - Pelatih Spanyol Luis de la Fuente me...,"Rabu, 16 Okt 2024 10:43 WIB",Sepak Bola,Jakarta Pelatih Spanyol Luis de la Fuente men...,jakarta pelatih spanyol luis de la fuente men...,"['jakarta', 'pelatih', 'spanyol', 'luis', 'de'...",jakarta pelatih spanyol luis de la fuente menu...,1

In [ ]:
from sklearn.model_selection import train_test_split

# Split data
x = df ['Hasil stopword']
y = df ['kategori_encoded']

print(x)
print(y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print("="*50)
print("Jumlah data latih:", len(x_train))
print("Jumlah data uji:", len(x_test))

0     jakarta rangkaian pertandingan ffws sea fall s...
1     jakarta ceo meta mark zuckerberg percaya kemam...
2     jakarta game horor daya tariknya penikmatnya b...
3     jakarta skin zhou yu honor of kings hok gratis...
4     jakarta tampil ribuan pendukungnya wakil indon...
                            ...
95    jakarta china vs indonesia tuntas lanjutan kua...
96    qingdao keputusan mencoret eliano reijnders me...
97    jakarta denzel dumfries mengakui performanya t...
98    jakarta matchday babak ketiga kualifikasi pial...
99    jakarta pelatih spanyol luis de la fuente menu...
Name: Hasil stopword, Length: 100, dtype: object
0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: kategori_encoded, Length: 100, dtype: int64
==================================================
Jumlah data latih: 80
Jumlah data uji: 20

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi TF-IDF Vectorizer
tfidf = TfidfVectorizer()

# Fit dan transform pada data training
x_train_tfidf = tfidf.fit_transform(x_train)

# Transform pada data testing
x_test_tfidf = tfidf.transform(x_test)

# Mendapatkan nama fitur dari TF-IDF
feature_names = tfidf.get_feature_names_out()

# Konversi TF-IDF hasil training ke DataFrame
df_train_tfidf = pd.DataFrame(x_train_tfidf.toarray(), columns=feature_names)

# Konversi TF-IDF hasil testing ke DataFrame
df_test_tfidf = pd.DataFrame(x_test_tfidf.toarray(), columns=feature_names)

# Tampilkan hasil TF-IDF dalam DataFrame
print("TF-IDF untuk data training:")
print(df_train_tfidf)

print("\nTF-IDF untuk data testing:")
print(df_test_tfidf)

TF-IDF untuk data training:
    aaa  abaaax  abaay  abdulla  abduweli  abduwelli  about  absen  abu   ac  \
0   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
1   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
2   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
3   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
4   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
..  ...     ...    ...      ...       ...        ...    ...    ...  ...  ...
75  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
76  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
77  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
78  0.0     0.0    0.0      0.0  0.214021        0.0    0.0    0.0  0.0  0.0
79  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0

    ...      zero    zhang  zhou  zombie      zona  zone  zoo  zubimendi  \
0   ...  0.000000  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0
1   ...  0.000000  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0
2   ...  0.031812  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0
3   ...  0.000000  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0
4   ...  0.000000  0.00000   0.0     0.0  0.061121   0.0  0.0        0.0
..  ...       ...      ...   ...     ...       ...   ...  ...        ...
75  ...  0.000000  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0
76  ...  0.000000  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0
77  ...  0.000000  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0
78  ...  0.000000  0.19586   0.0     0.0  0.000000   0.0  0.0        0.0
79  ...  0.000000  0.00000   0.0     0.0  0.000000   0.0  0.0        0.0

    zuckerberg  zwolle
0          0.0     0.0
1          0.0     0.0
2          0.0     0.0
3          0.0     0.0
4          0.0     0.0
..         ...     ...
75         0.0     0.0
76         0.0     0.0
77         0.0     0.0
78         0.0     0.0
79         0.0     0.0

[80 rows x 3718 columns]

TF-IDF untuk data testing:
    aaa  abaaax  abaay  abdulla  abduweli  abduwelli  about  absen  abu   ac  \
0   0.0     0.0    0.0      0.0  0.057301        0.0    0.0    0.0  0.0  0.0
1   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
2   0.0     0.0    0.0      0.0  0.066845        0.0    0.0    0.0  0.0  0.0
3   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
4   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
5   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
6   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
7   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
8   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
9   0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
10  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
11  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
12  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
13  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
14  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
15  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
16  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
17  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
18  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0
19  0.0     0.0    0.0      0.0  0.000000        0.0    0.0    0.0  0.0  0.0

    ...  zero     zhang  zhou  zombie      zona  zone  zoo  zubimendi  \
0   ...   0.0  0.052438   0.0     0.0  0.000000   0.0  0.0        0.0
1   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
2   ...   0.0  0.000000   0.0     0.0  0.059571   0.0  0.0        0.0
3   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
4   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
5   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
6   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
7   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
8   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
9   ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
10  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
11  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
12  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
13  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
14  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
15  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
16  ...   0.0  0.000000   0.0     0.0  0.208094   0.0  0.0        0.0
17  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
18  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0
19  ...   0.0  0.000000   0.0     0.0  0.000000   0.0  0.0        0.0

    zuckerberg  zwolle
0          0.0     0.0
1          0.0     0.0
2          0.0     0.0
3          0.0     0.0
4          0.0     0.0
5          0.0     0.0
6          0.0     0.0
7          0.0     0.0
8          0.0     0.0
9          0.0     0.0
10         0.0     0.0
11         0.0     0.0
12         0.0     0.0
13         0.0     0.0
14         0.0     0.0
15         0.0     0.0
16         0.0     0.0
17         0.0     0.0
18         0.0     0.0
19         0.0     0.0

[20 rows x 3718 columns]

In [ ]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# # Menginisialisasi TfidfVectorizer
# vectorizer = TfidfVectorizer()

# # Menghitung TF-IDF
# train_tfidf_matrix = vectorizer.fit_transform(x_train)
# test_tfidf_matrix = vectorizer.fit_transform(x_test)


# # Mengubah hasilnya menjadi DataFrame
# tfidf_df = pd.DataFrame(train_tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())
# tfidf_df.head(10)
# # Menyimpan hasil ke file CSV
# tfidf_df.to_csv('hasil_tfidf.csv', index=False)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Membuat model Logistic Regression dengan regularisasi
model = LogisticRegression(max_iter=1000, C=0.2)  # Mengurangi nilai C untuk menambah regularisasi

# Melatih model dengan data yang sudah diresample (jika diperlukan)
model.fit(x_train_tfidf, y_train)

# Memprediksi hasil pada data testing
y_pred = model.predict(x_test_tfidf)

In [ ]:
# Evaluasi hasil prediksi
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Menampilkan laporan klasifikasi
print(classification_report(y_test, y_pred))

Accuracy: 90.00%
              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      1.00      0.89         8

    accuracy                           0.90        20
   macro avg       0.90      0.92      0.90        20
weighted avg       0.92      0.90      0.90        20

In [ ]:
import joblib

# Menyimpan model Logistic Regression
joblib.dump(model, 'logistic_regression_model.joblib')

# Menyimpan model TF-IDF Vectorizer
joblib.dump(tfidf, 'tfidf_model.joblib')

print("Model Logistic Regression dan TF-IDF telah disimpan dengan joblib.")

Model Logistic Regression dan TF-IDF telah disimpan dengan joblib.

In [ ]:
# Menyimpan tfidf_matrix dan vectorizer menggunakan pickle
with open('tfidf_vectorizer.pkl', 'wb') as file:
    joblib.dump(tfidf, file)
# Menyimpan model ke dalam file pickle
with open('logistic_regression_model.pkl', 'wb') as file:
    joblib.dump(model, file)

**PENGUJIAN**

---

In [ ]:
import joblib

# Memuat vectorizer dan model
tfidf = joblib.load('tfidf_vectorizer.pkl')
model = joblib.load('logistic_regression_model.pkl')

In [ ]:
import joblib

# Teks baru yang ingin diprediksi
new_text_1 = ['''
Jakarta - Game horor selalu punya daya tariknya sendiri, sehingga membuat sebagian penikmatnya betah memainkannya dalam waktu yang lama. Beberapa dari mereka ada yang kecanduan dengan nuansa mencekamnya, atau penasaran dengan alur ceritanya. Namun memang tidak semua gamer bisa mengonsumsi kengerian yang diberikan para pengembang game horor. Tak sedikit dari mereka yang menghindari visual menyeramkannya, atau suara kejutan yang bisa menyiksa jantung para pemainnya. Namun memang hal itu lah yang menjadi pembeda antara game horor dengan genre lainnya. Meski tidak selalu menawarkan adegan bertarung dengan penuh gaya, genre yang satu ini punya siasat lain dalam upaya memberikan keseruan kepada para pemain. Nah dari sekian banyak game horor yang telah dirilis oleh para pengembang di luar sana, gamer sudah main apa saja? Pasti Resident Evil menjadi salah satu favorit sepanjang masa. Tapi tahukah detikers, tidak hanya seri Resident Evil yang dapat memberikan keseruan dalam bermain game horor. Banyak sekali gamer horor terbaik yang diluncurkan sepanjang tahun 2000an. Hampir semuanya bagus, dan layak dicoba. Jadi apa game horor terbaik tahun 2000an yang sudah pernah kalian mainkan? Pasti ada beberapa judul yang melekat di hati kalian, karena menjadi pemicu kecintaan terhadap genre seram ini. Di sini, detikINET sudah mengumpulkan 20 game horor terbaik tahun 2000an , yang bisa kalian coba mainkan. Itu pun kalau kalian merasa menjadi pemain paling berani. Berikut informasinya, sebagaimana dihimpun dari The Gamer, Rabu (16/10/2024). Game Horor Terbaik Tahun 2000an 1. Call Of Cthulhu: Dark Corners Of The Earth Platform: PC dan Xbox Pengembang: Headfirst Productions Penerbit: Bethesda Softworks dan 2K Games 2. The Suffering Platform: PC, PS2, dan Xbox Pengembang: Surreal Software Penerbit: Midway Games dan Zoo Digital Publishing 3. Cold Fear Platform: PC, PS2, dan Xbox Pengembang: Darkworks Penerbit: Ubisoft 4. Siren Platform: PS3 dan PS4 Pengembang: Japan Studio Penerbit: Sony Computer Entertainment 5. Martian Gothic: Unification Platform: PC dan PlayStation Pengembang: Creative Reality Penerbit: TalonSoft, Take-Two Interactive, Buka Entertainment, dan Take-Two Interactive Software Europe Ltd 6. Clive Barker's Undying Platform: PC Pengembang: DreamWorks Interactive dan Westlake Interactive Penerbit: Electronic Arts dan Aspyr 7. Penumbra: Overture Platform: PC Pengembang: Frictional Games Penerbit: Frictional Games 8. Saw: The Video Game Platform: PS3, Xbox 360, dan Microsoft Windows Pengembang: Zombie Studios Penerbit: Konami dan Brash Entertainment 9. Obscure Platform: PC. PS2, dan Xbox Pengembang: Hydravision Entertainment Penerbit: DreamCatcher Interactive 10. F.E.A.R. Platform: PC, PS3, dan Xbox 360 Pengembang: Monolith Productions Penerbit: Vivendi Universal 11. Haunting Ground Platform: PS2 dan PS3 Pengembang: Capcom Penerbit: Capcom 12. Dead Rising Platform: PC, PS4, Xbox 360, dan Xbox One Pengembang: Capcom Penerbit: Capcom 13. Condemned: Criminal Origins Platform: PC dan Xbox 360 Pengembang: Monolith Productions Penerbit: Sega 14. Fatal Frame 2: Crimson Butterfly Platform: PS2, PS3, Wii, dan Xbox Pengembang: Tecmo Penerbit: Tecmo 15. Eternal Darkness: Sanity's Requiem Platform: GameCube Pengembang: Silicon Knights Penerbit: Nintendo 16. Dead Space Platform: PC, PS3, dan Xbox 360 Pengembang: Visceral Games Penerbit: Electronic Arts 17. BioShock Platform: PC, PS3, dan Xbox 360 Pengembang: Irrational Games Penerbit: 2K Games 18. Resident Evil 4 Platform: PS4, PS3, PS2, Xbox One, Xbox 360, Switch, Wii, Nintendo GameCube, PC, Android, dan iOS Pengembang: Capcom Penerbit: Capcom 19. Resident Evil (2002) Platform: GameCube dan Wii Pengembang: Capcom Production Studio 4 Penerbit: Capcom 20. Silent Hill 2, 3, And 4 Platform: PC, PS2, PS3, Xbox, dan Xbox 360 Pengembang: Konami Penerbit: Konami (hps/fay)
''']

new_text_2 = ['''
Manchester - Paul Gascoigne menyarankan Marcus Rashford pindah ke Italia. Beberapa pemain yang redup bersama Manchester United kerap kali menemuikan sinarnya di Serie A . Marcus Rashford banyak dikritik usai tampil buruk bersama MU di awal musim ini. Ia baru mampu mengemas satu gol di Liga Inggris musim ini. Buruknya perfoma Rashford turut mempengaruhi laju MU. Setan Merah jeblok dengan berada di peringkat ke-14 dengan baru meraih delapan angka. Legenda Inggris, Paul Gascoigne, menyarankan Rashford pindah ke Serie A melihat situasi yang dihadapinya di MU. Ia menilai Rashford saat ini telah kehilangan kebahagiaan saat bermain bola. Gascoigne yakin Rashford bakal menemukan kembali kebahagian itu jika bermain Italia. Gascoigne sendiri pernah bermain di Serie A bersama Lazio pada rentang 1992-1995 usai pindah dari Tottenham Hotspur. Beberapa mantan pemain MU juga berhasil bersinar lagi usai pindah ke Serie A. Sebut saja Chris Smalling, Romelu Lukaku, dan teranyar Scott McTominay. McTominay yang banyak dikritik di MU justru jadi andalan Napoli di musim ini. "Saya suka Rashford, saya pikir dia pemain yang luar biasa, tetapi dia tampaknya memperhatikan itu," kata Gascoigne kepada SportsCasting. "Bahkan ketika dia mencetak gol, dia tampak tidak senang dengan hal itu, jadi ada sesuatu yang terjadi di sana." "Jika itu masalahnya, pindah saja. Anda mendapatkan beberapa pemain yang pindah dan kemudian mereka menemukan sesuatu yang berbeda. Untuk Rashford, dia tampaknya tidak senang bermain di Inggris. Dan beberapa klub bagus akan datang untuknya. Pergi ke Italia, itu akan mengejutkannya," jelasnya. (pur/krs)
''']

# Load the saved vectorizer and model
tfidf = joblib.load('tfidf_vectorizer.pkl')
model = joblib.load('logistic_regression_model.pkl')

# New texts to predict
new_text = new_text_1 + new_text_2

# Preprocess and transform using the loaded TF-IDF vectorizer
new_text_tfidf = tfidf.transform(new_text)

# Predict using the Logistic Regression model
predictions = model.predict(new_text_tfidf)

# Map predictions to categories
predicted_categories = ["Games" if prediction == 0 else "Sepak Bola" for prediction in predictions]

# Output the predictions
for i, category in enumerate(predicted_categories):
    print(f"Prediction for text {i+1}: {category}")

Prediction for text 1: Games
Prediction for text 2: Sepak Bola

Test 1

Jakarta - Dalam ranking FIFA terbaru, Jepang masih perkasa sebagai tim Asia dengan peringkat tertinggi. Pasukan Samurai Biru ada di peringkat ke-16!
FIFA merilis ranking FIFA terbaru per September 2024 pada Jumat (19/9). Untuk di level Asia, Jepang masih menempati peringkat teratas.
Timnas Jepang duduk di peringkat ke-16 ranking FIFA terbaru dengan 1639.6 poin. Wataru Endo dkk naik dua peringkat.
epang mampu sapu bersih dua kemenangan di dua laga awal ronde ketiga Kualifikasi Piala Dunia 2026 Zona Asia. Jepang pesta gol atas China 7-0 dan cukur Bahrain 5-0.
Jepang pun menjadi satu-satunya tim dengan poin sempurna sejauh ini di Grup C dengan enam poin. Mereka disusul Arab Saudi (empat poin), Bahrain (tiga poin), dan Indonesia (dua poin).

Test 2

Jakarta - Sekitar satu dekade lalu internet terobsesi dengan game mobile Flappy Bird yang bikin ketagihan. Setelah menghilang cukup lama, game viral ini akan kembali lagi dengan membawa sejumlah pembaruan.
Reinkarnasi Flappy Bird dipelopori oleh sekumpulan penggemar yang tergabung dalam Flappy Bird Foundation. Mereka berhasil memperoleh hak cipta atas game ini dari Gametech, LLC, yang tidak memiliki hubungan dengan pencipta asli Flappy Bird, Dong Nguyen.
Game Flappy Bird akan tersedia untuk Android dan iOS mulai tahun 2025,
 tapi game ini akan bisa dimainkan di platform lain sebelum tanggal tersebut.
Tim Flappy Bird Foundation berencana menghadirkan game ini ke platform seperti desktop dan mobile web mulai musim gugur tahun ini.